// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGTS7FqLmaGvKPQNPNyZZh3nKtBaqosvk',
    appId: '1:182702470202:web:520da90d5a66ea3b877103',
    messagingSenderId: '182702470202',
    projectId: 'parent-teacher-meet',
    authDomain: 'parent-teacher-meet.firebaseapp.com',
    databaseURL: 'https://parent-teacher-meet-default-rtdb.firebaseio.com',
    storageBucket: 'parent-teacher-meet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYbluz5PmONdT04TnTg9b0lyJX62fQIlc',
    appId: '1:182702470202:android:db284ffd8e372ee3877103',
    messagingSenderId: '182702470202',
    projectId: 'parent-teacher-meet',
    databaseURL: 'https://parent-teacher-meet-default-rtdb.firebaseio.com',
    storageBucket: 'parent-teacher-meet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVqKO8cSxnyw8wml6i1ofB_JLxiJE6CWc',
    appId: '1:182702470202:ios:79f79e6d7065c7f8877103',
    messagingSenderId: '182702470202',
    projectId: 'parent-teacher-meet',
    databaseURL: 'https://parent-teacher-meet-default-rtdb.firebaseio.com',
    storageBucket: 'parent-teacher-meet.appspot.com',
    androidClientId: '182702470202-8lr9i2m9ueeta06grnelfook0hfd5hrn.apps.googleusercontent.com',
    iosClientId: '182702470202-f4k7mfku3lkdkmdvbhj6u43rf9e834tk.apps.googleusercontent.com',
    iosBundleId: 'com.PtaMeeting.meetings',
  );
}
